name: butter-chicken cd pipeline
run-name: ${{ github.actor }} is pushing on main-branch
on: [push]
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:  # This 'steps' key is necessary to contain the steps that the job will execute
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # wird automatisch generiert
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: tictactoe-image:latest

#  build-and-deploy:
 #   runs-on: ubuntu-latest
  #  steps:
   #   - name: Checkout Code
    #    uses: actions/checkout@v4
     # - name: Install Dependencies
      #  run: npm ci
 #     - name: Build
  #      run: npm run build
   #   - name: Deploy
    #    uses: JamesIves/github-pages-deploy-action@v4
     #   with:
      #    folder: dist # The folder the action should deploy.
